- id: '1572136269658'
  alias: Doorbird Doorbell
  trigger:
  - event_data: {}
    event_type: doorbird_gate_doorbell
    platform: event
  condition: []
  action:
  - device_id: 7a42f4da1d944679a19b8e795cd09578
    domain: light
    entity_id: light.hue_color_lamp_2
    type: toggle
  - device_id: 1fa4d3bef9f9489398d0edc4cd805c57
    domain: light
    entity_id: light.hue_color_lamp_3
    type: toggle
  - device_id: 981fbf9e2fcc4451a17009a58c9943a8
    domain: light
    entity_id: light.hue_color_lamp_1
    type: toggle
  - timeout: '1'
    wait_template: ''
  - device_id: 1fa4d3bef9f9489398d0edc4cd805c57
    domain: light
    entity_id: light.hue_color_lamp_3
    type: toggle
  - device_id: 7a42f4da1d944679a19b8e795cd09578
    domain: light
    entity_id: light.hue_color_lamp_2
    type: toggle
  - device_id: 981fbf9e2fcc4451a17009a58c9943a8
    domain: light
    entity_id: light.hue_color_lamp_1
    type: toggle
  - timeout: '1'
    wait_template: ''
  - device_id: 1fa4d3bef9f9489398d0edc4cd805c57
    domain: light
    entity_id: light.hue_color_lamp_3
    type: toggle
  - device_id: 7a42f4da1d944679a19b8e795cd09578
    domain: light
    entity_id: light.hue_color_lamp_2
    type: toggle
  - device_id: 981fbf9e2fcc4451a17009a58c9943a8
    domain: light
    entity_id: light.hue_color_lamp_1
    type: toggle
  - timeout: '1'
    wait_template: ''
  - device_id: 1fa4d3bef9f9489398d0edc4cd805c57
    domain: light
    entity_id: light.hue_color_lamp_3
    type: toggle
  - device_id: 7a42f4da1d944679a19b8e795cd09578
    domain: light
    entity_id: light.hue_color_lamp_2
    type: toggle
  - device_id: 981fbf9e2fcc4451a17009a58c9943a8
    domain: light
    entity_id: light.hue_color_lamp_1
    type: toggle
- id: '1572162265311'
  alias: Doorbird Open
  description: ''
  trigger:
  - event_data: {}
    event_type: doorbird_gate_relay_unlocked
    platform: event
  condition: []
  action: []
- id: '1572222668802'
  alias: Terrell Gate
  description: ''
  trigger:
  - payload: Terrell Hines
    platform: mqtt
    topic: shairport/artist
  condition: []
  action:
  - data:
      entity_id: switch.gate_relay_1
    service: switch.turn_on
- id: '1572669799416'
  alias: LivingRoomLightSwitch_Up1
  description: Single Click up
  trigger:
  - event_data:
      entity_id: zwave.inovelli_lzw30_sn_switch_red_series
      node_id: 4
      scene_data: 7680
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - alias: ''
    data:
      group_name: Living room
      scene_name: Read
    service: hue.hue_activate_scene
- id: '1572715380986'
  alias: LivingRoomLightSwitch_Down1
  description: Single Click Down
  trigger:
  - event_data:
      entity_id: zwave.inovelli_lzw30_sn_switch_red_series
      node_id: 4
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.living_room
    service: light.turn_off
- id: '1572716237368'
  alias: LivingRoomLightSwitch_Config
  description: Config button to open gate 2 min
  trigger:
  - event_data:
      entity_id: zwave.inovelli_lzw30_sn_switch_red_series
      node_id: 4
      scene_data: 7680
      scene_id: 3
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      node_id: 4
      parameter: 8
      size: 4
      value: 71174700
    service: zwave.set_config_parameter
  - data:
      entity_id: switch.gate_relay_1
    service: switch.turn_on
  - timeout: '30'
    wait_template: ''
  - data:
      entity_id: switch.gate_relay_1
    service: switch.turn_on
  - timeout: '30'
    wait_template: ''
  - data:
      entity_id: switch.gate_relay_1
    service: switch.turn_on
  - timeout: '15'
    wait_template: ''
  - data:
      entity_id: switch.gate_relay_1
    service: switch.turn_on
- id: '1573095303826'
  alias: LivingRoomLightSwitch_Up3
  description: Double click 3
  trigger:
  - event_data:
      entity_id: zwave.inovelli_lzw30_sn_switch_red_series
      node_id: 4
      scene_data: 7920
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      group_name: Living room
      scene_name: Movie
    service: hue.hue_activate_scene
- id: '5430980073746'
  alias: LivingRoomLightSwitch_Up2
  description: Double Click up
  trigger:
  - event_data:
      entity_id: zwave.inovelli_lzw30_sn_switch_red_series
      node_id: 4
      scene_data: 7860
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - device_id: bb74a122851a429584f9f1ae8d350223
    domain: light
    entity_id: light.inovelli_unknown_type_0005_id_0001_level
    type: turn_on
  - device_id: 207a4b74c2ff4400998a7058a9f004f1
    domain: light
    entity_id: light.inovelli_lzw31_sn_dimmer_red_series_level
    type: turn_on
- id: '5430980073745'
  alias: LivingRoomLightSwitch_Down2
  description: Double Click Down
  trigger:
  - event_data:
      entity_id: zwave.inovelli_lzw30_sn_switch_red_series
      node_id: 4
      scene_data: 7860
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - device_id: bb74a122851a429584f9f1ae8d350223
    domain: light
    entity_id: light.inovelli_unknown_type_0005_id_0001_level
    type: turn_off
  - device_id: 207a4b74c2ff4400998a7058a9f004f1
    domain: light
    entity_id: light.inovelli_lzw31_sn_dimmer_red_series_level
    type: turn_off
- id: '1578457993258'
  alias: BedroomLightSwitch_Up1
  description: ''
  trigger:
  - event_data:
      node_id: 10
      scene_data: 7680
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - alias: ''
    data:
      group_name: Marley Bedroom
      scene_name: Concentrate
    service: hue.hue_activate_scene
- id: '1578458437376'
  alias: BedroomLightSwitch_Down1
  description: ''
  trigger:
  - event_data:
      node_id: 10
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.hue_color_lamp_4
    service: light.turn_off
- id: '1578523199911'
  alias: GarageLightSwitch_Up1
  description: ''
  trigger:
  - event_data:
      node_id: 8
      scene_data: 7680
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - scene: scene.garage_party
- id: '1578523221836'
  alias: GarageLightSwitch_Down1
  description: ''
  trigger:
  - event_data:
      node_id: 8
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - scene: scene.garage_off
- id: '1578636161760'
  alias: GarageLightSwitch_Up2
  description: ''
  trigger:
  - event_data:
      node_id: 8
      scene_data: 7860
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - scene: scene.garage_work
- id: '1578717784283'
  alias: LivingRoomLightSwitch_Down3
  description: Turn Off Garage
  trigger:
  - event_data:
      node_id: 4
      scene_data: 7920
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - scene: scene.garage_off
- id: '1578717900299'
  alias: LivingRoomLightSwitch_Up4
  description: ''
  trigger:
  - event_data:
      node_id: 4
      scene_data: 7980
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - scene: scene.garage_party
- id: '1578727093819'
  alias: Bedroom Notification Light
  description: Set Zwave alert trigger if any lights in the garage group are on.
  trigger:
  - entity_id: group.garage
    platform: state
    to: 'on'
  condition: []
  action:
  - service: zwave.set_config_parameter
    data:
      node_id: 10
      parameter: 14
      value: 100%
- id: '1578889509148'
  alias: Bedroom Notification Light Off
  description: ''
  trigger:
  - entity_id: group.garage
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      node_id: 10
      parameter: 14
      value: 0%
    service: zwave.set_config_parameter
- id: '1579473499259'
  alias: KitchenDimmer_Up1
  description: KitchenDimmer Up 1 turns on Dining Room Light
  trigger:
  - event_data:
      node_id: 12
      scene_data: 7680
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - device_id: bb74a122851a429584f9f1ae8d350223
    domain: light
    entity_id: light.inovelli_unknown_type_0005_id_0001_level
    type: turn_on
- id: '1579473586044'
  alias: KitchenDimmer_Down1
  description: ''
  trigger:
  - event_data:
      node_id: 12
      scene_data: 7680
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - device_id: bb74a122851a429584f9f1ae8d350223
    domain: light
    entity_id: light.inovelli_unknown_type_0005_id_0001_level
    type: turn_off
- id: '1579508459994'
  alias: All Off trigger
  description: Turn off All lights. Pause Garage Music if on.
  trigger:
  - event_data:
      actionName: All Off
    event_type: ios.action_fired
    platform: event
  - event_data:
      node_id: 4
      scene_data: 8040
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      event_data:
        node_id: 8
        scene_data: 8040
        scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      event_data:
        node_id: 10
        scene_data: 8040
        scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  - event_data:
      event_data:
        node_id: 12
        scene_data: 8040
        scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - scene: scene.garage_off
  - scene: scene.living_lights_off
  - scene: scene.bedroom_lights_off
